Add Playground#html
- `rails g migration AddHtmlToPlaygrounds html:string`
- `RAILS_ENV=test rails db:migrate`

Fixes:

```
1) Playground should have db column named html
     Failure/Error: it { is_expected.to have_db_column(:html) }
       Expected Playground to have db column named html (Playground does not have a db column named html.)
     # ./spec/models/playground_spec.rb:4:in `block (2 levels) in <top (required)>'

  2) Creating a new Playground as a visitor
     Failure/Error: <%= f.input :html %>

     ActionView::Template::Error:
       undefined method `html' for #<Playground:0x007fc731146810>
```