Implement Playground#css
- `rails g migration AddCssToPlaygrounds css:string`
- `RAILS_ENV=test rails db:migrate`

Fixes:
```
1) Creating a new Playground as a visitor
     Failure/Error: <%= f.input :css %>

     ActionView::Template::Error:
       undefined method `css' for #<Playground:0x007fdff9363ba8>
     # ./app/views/playgrounds/new.html.erb:3:in `block in _app_views_playgrounds_new_html_erb___4204673798256425772_70299967475560'
     # ./app/views/playgrounds/new.html.erb:1:in `_app_views_playgrounds_new_html_erb___4204673798256425772_70299967475560'
     # ./spec/features/creating_a_new_playground_spec.rb:5:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # NoMethodError:
     #   undefined method `css' for #<Playground:0x007fdff9363ba8>
     #   ./app/views/playgrounds/new.html.erb:3:in `block in _app_views_playgrounds_new_html_erb___4204673798256425772_70299967475560'

  2) Playground should have db column named css
     Failure/Error: it { is_expected.to have_db_column(:css) }
       Expected Playground to have db column named css (Playground does not have a db column named css.)
     # ./spec/models/playground_spec.rb:5:in `block (2 levels) in <top (required)>'
```